/* Suit-variant hero images — one per accent in ACCENT_POOL.
   Generated by scripts/recolor-suit.mjs: a DETERMINISTIC recolor of
   the original photos, so every variant is pixel-identical to the
   base image except the suit, which takes the accent's hue (the real
   face, shirt, hands, background and the cutout's alpha never move).
   The one exception is "mono" (Black & White), generated by
   scripts/make-mono.mjs — the WHOLE photo desaturated to true
   grayscale, because a monochrome theme deserves a monochrome hero.
   Keep the id list in sync with src/lib/accent-pool.ts. */

export const HERO_ACCENT_IDS = [
  "purple",
  "indigo",
  "teal",
  "deep-orange",
  "pink",
  "cyan",
  "amber",
  "deep-purple",
  "green",
  "blue",
  "mono",
] as const;

export type HeroAccentId = (typeof HERO_ACCENT_IDS)[number];

export const PORTRAIT_BASE = "/generated/m-rayhan-portrait-hd.webp";
export const CUTOUT_BASE = "/generated/m-rayhan-cutout-lossless.webp";

export const portraitVariant = (id: string) =>
  `/generated/m-rayhan-portrait-hd-${id}.webp`;
export const cutoutVariant = (id: string) =>
  `/generated/m-rayhan-cutout-${id}.webp`;
